name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --build-arg UID=${UID:-1000} --build-arg GID=${GID:-1000} ./dockerfiles --file ./dockerfiles/nginx.dockerfile --tag my-image-name:$(date +%s)
